public with sharing class Homework {
    // Declare a variable to hold the postcode of Ginetta House - as
    // the office cannot move, this should be immutable


    // Declare a string that is initialised from an Integer


    public void newYearsEve()
    {
        // Create a variable representing the time 12:30:25 in the local 
        // timezone and use this time to create a DateTime for the date 
        // 12/31/2021
    }

    public void castAccount()
    {
        // Create an sobject variable initialised to a new Account. 
        // Create an account variable that is initialised by casting the 
        // sobject variable.
    }    

    public void createBlob()
    {
        // Create a Blob from the characters ‘I am a Blob’
    }

    public void createId()
    {
        // Create an ID with the value ‘00D180000001s0LEAQ', convert 
        // this to the 15 character version.
    }

    public void sliceOfPi()
    {
        // Create a Decimal with the value of PI to 5 decimal places.
        
        // Use the built-in method to convert it to 2 decimal places.
    }

    public void whitespace()
    {
        // Create a String variable. 

        // Assign it the value ‘     BrightGen Limited   ‘. 
        
        // Use a built-in method to create a new String with the 
        // whitespace at the start and end removed.
    }

    public void intFromDouble()
    {
        // Create a Double with a value of 100.245. 
        
        // Convert this to an integer using a built-in method
        
        // Convert this to another integer using casting.

    }


    public void twoAtOnce()
    {
        // Declare two Integers, with the values 6 and 7, in a single 
        // statement.
    }

    public void booleanFromString()
    {
        // Create a boolean whose value is initialised from the text
        // ‘true’.
    }

    public void reverse()
    {
        // Create a string with the value ‘1234567890’ 
        
        // Use a built-in method to convert to ‘0987654321’
    }

    public void findApex(String candidate) 
    {
        // Find the position of the substring “Apex” in candidate
    }

    public void get10And15(String candidate)
    {
        // Extract the 10th and 15th characters from a string

    }

    public void monthsBetween(Date startDate)
    {
        // Create variable endDate for 25/12/2024
        
        // Use a built-in method to determine the number of months 
        // between the start and end dates.

    }
}